export default {
  FETCH_TRACK_LIST: 'FETCH_TRACK_LIST',
  FETCH_TRACK_LIST_DONE: 'FETCH_TRACK_LIST_DONE',
  FETCH_TRACK_LIST_FAILED: 'FETCH_TRACK_LIST_FAILED',
  PLAY_REQUEST: 'PLAY_REQUEST',
  PLAY_REQUEST_SUCCSESS: 'PLAY_REQUEST_SUCCESS',
  PLAY_REQUEST_FAILED: 'PLAY_REQUEST_FAILED',
  TOGGLE_PLAYER: 'TOGGLE_PLAYER',
  CHANGE_TRACK: 'CHANGE_TRACK',
};
